### ISSUE TITLE
Add navigation

### ISSUE THREAD

**Issue by eileenfuerstenau** [eileenfuerstenau/capstone#12]
**Value proposition (user story)**

As a user
I want to navigate to another oage
in order to see an inspirational quote about reading 

**Description (text, scribble, design)**

<img width="460" alt="6th user story" src="https://user-images.githubusercontent.com/77294653/111076588-2b176080-84ed-11eb-8eec-851c34da6183.png">

**Acceptance criteria (edge cases)**

- [x] Navbar on page bottom
- [x] Clickable icons that change color when active
- [x] Second page with inspirational quote 

Complexity (S, M, L)

M

**Tasks**

- [x] Create feature branch
- [x] Create app grid (storybook)
- [x] Create navbar (storybook)
- [x] Create second page 
- [x] Add routing functionality
- [x] Add testing
