### ISSUE TITLE
Implement Localstorage

### ISSUE THREAD

**Issue by eileenfuerstenau** [eileenfuerstenau/capstone#25]
**Value proposition (user story)**

As a user
I want to see a header with a page title
in order to know what page i am on and have a better UX 

**Description (text, scribble, design)**

Header on top of each page

**Acceptance criteria (edge cases)**

- [x] Renders a header with a title

**Complexity (S, M, L)**

S

**Tasks**

- [x] Create feature branch
- [x] Create header component (storybook)
- [x] Implement header with respective title to each page
- [x] Write test
