### ISSUE TITLE
Set Up Backend

### ISSUE THREAD

**Issue by eileenfuerstenau** [eileenfuerstenau/capstone#26]
**Value proposition (user story)**

As a user
I want to save votes and share with my friends 
in order to decide together what to read next

**Description (text, scribble, design)**

Implement backend as a preparation for the voting functionality

<img width="176" alt="10th user story" src="https://user-images.githubusercontent.com/77294653/113201272-99884c80-9269-11eb-879c-d468e1ca2158.png">

**Acceptance criteria (edge cases)**

- [x] Postman GET/ POST Requests to backend work

**Complexity (S, M, L)**

M

**Tasks**

- [x] Create feature branch
- [x] install mongoose, express, nodemon, dotenv
- [x] Add Models
- [x] Add Routes
- [x] Add Serverfunctions for GET/ POST Requests
