### ISSUE TITLE
Implement Delete Function on Voting Page

### ISSUE THREAD

**Issue by eileenfuerstenau** [eileenfuerstenau/capstone#27]
**Value proposition (user story)**

As a user
I want to be able to delete accidentally nominated books
in order to clean up the shortlist

**Description (text, scribble, design)**

Delete Icons on each Bookcard on the Voting Page

<img width="181" alt="11th user story" src="https://user-images.githubusercontent.com/77294653/113201238-92613e80-9269-11eb-98fb-7ce8fb6f00ca.png">

**Acceptance criteria (edge cases)**

- [x] Deletes Card on click

**Complexity (S, M, L)**

M

**Tasks**

- [x] Create feature branch
- [x] Add Delete Icon
- [x] Implement Delete Function
